*** Variables ***
${EMAIL_INPUT}      xpath=//*[@data-testid="email-input"]
${PASSWORD_INPUT}   xpath=//*[@data-testid="password-input"]
${EXERCISE_INPUT}   xpath=//*[@data-testid="exercise-input"]
${WEIGHT_INPUT}     xpath=//*[@data-testid="weight-input"]
${REPS_INPUT}       xpath=//*[@data-testid="reps-input"]
${SETS_INPUT}       xpath=//*[@data-testid="sets-input"]
${DATE_INPUT}       xpath=//*[@data-testid="date-input"]

${ROW}              xpath=//*[@data-testid="log-row"]
${LOGIN_BTN}        xpath=//*[@data-testid="login-btn"]
${REGISTER_BTN}     xpath=//*[@data-testid="register-btn"]
${LOGOUT_BTN}       xpath=//*[@data-testid="logout-btn"]
${MENU_BTN}         xpath=//*[@data-testid="menu-btn"]
${SUBMIT_BTN}       xpath=//*[@data-testid="submit-btn"]
${EDIT_BTN}         xpath=//*[@data-testid="edit-btn"]
${DELETE_BTN}       xpath=//*[@data-testid="delete-btn"]
${SAVE_BTN}         xpath=//*[@data-testid="save-btn"]
${CANCEL_BTN}       xpath=//*[@data-testid="cancel-btn"]